### ISSUE TITLE
Change distal_link on-line

### ISSUE THREAD

**Issue by EnricoMingo** [ADVRHumanoids/CartesianInterface#38]
We have recently considered the possibility to change the ```distal_link``` name on the fly in our Cartesian tasks. This creates a series of issues related on how we handle the tasks, topics names and so on.
In particular: the task ```distal_link``` at the moment is also the topic name which eventually may change if we implement the possibility to change it. This is not wanted of course.
A possible solution could be to use the task name as topic name. 

Another point is to refactor a little the yaml creation so that sub tasks are particular types of tasks which refers to tasks that are already defined. Something like:
```
T1:
 type: Cartesian 
 base_link: sossio
 distal_link: aruta
 ...

S1:
 type: SubTask
 base_task: T1
 indices: [1, 3]
```
