### ISSUE TITLE
Set Name field also for subtasks

### ISSUE THREAD

**Issue by torydebra** [ADVRHumanoids/CartesianInterface#79]
At the moment it seems that the name of the subtask cannot be changed and it is always the key of the yaml

For example: 
```yaml
RightArm:
    type: "Cartesian"
    name: "right_arm"
    #distal_link: "arm2_8"

RightArmLinear:
    type: "Subtask"
    task: "RightArm"
```

Results in having the topics : 
```bash
/cartesian/right_arm/***
/cartesian/RightArmLinear/***
```
